export const loginBtnStyles = {
  w: "100%",
  h: "8xl",
  p: "l",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: "2xs",
  rounded: "l2",
  border: "1px solid",
  borderColor: "black",
  color: "black",
  fontWeight: "600",
  fontSize: "step -1",
  bg: "white",
};

export const emailLoginBtnStyles = {
  w: "100%",
  h: "8xl",
  p: "l",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: "2xs",
  rounded: "l2",
  border: "1px solid",
  borderColor: "goldFang.solid.600",
  color: "goldFang.solid.50",
  fontWeight: "600",
  fontSize: "step -1",
  bg: "goldFang.solid.950",
};
